// object literal => store key=value pairs
// const address ={
//     country:'turkey',
//     city: 'istanbul',
// };
// console.log(address)
// console.log(address.city,"is very good for it")
// console.log(`${address.city}`,"is very good for it")
// const person={
//     name:'sam',
//     age:31,
//     'full address':'athens,grace',
//     job:"camptain america",
//     1985:"dob"
// };
// console.log(person.age)
//modifying ojects => chane the object data
// const moviesratings={
//     "x=man":7.9,
//     "thor":6.4,
//     "wonder woman":9,
//     superman:9,
// };

// moviesratings["x=man"]=9.8
// moviesratings.superman=5.4
// console.log(moviesratings)

// //updating objects => create more key-value pairs
// moviesratings["the end"]=5,9
// moviesratings["start up"]=7.9
// console.log(moviesratings)
